title: Jan Groeschel
description: Organisational Psychologist (Provisional)
site_title: 'Jan Groeschel | Organisational Psychologist'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: placeholder
blog_url: https://jan.groeschel.com.au/
email: jan[at]groeschel.com.au
keybase_username: placeholder
twitter_username: placeholder
reddit_username: placeholder

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: G-C23FFSVZXT