title: Jan Groeschel
description: Organisational Psychologist (Provisional)
site_title: 'Jan Groeschel | Organisational Psychologist'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://jan.groeschel.com.au/
email: jan[at]groeschel.com.au
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 